/**
 * 
 */
loadJs("test/msLinq-base.test.js")
loadJs("test/msLinq-lambda.test.js")
loadJs("test/msLinq-aggregate.test.js");
loadJs("test/msLinq-all.test.js")
loadJs("test/msLinq-any.test.js")
loadJs("test/msLinq-average.test.js")
loadJs("test/msLinq-concat.test.js")